export const VALID_METRICS = [
  'TIEMPO_MAXIMO_COCINA_MINUTOS',
  'TIEMPO_MAXIMO_VIAJE_DELIVERY',
  'TIEMPO_MAXIMO_ESPERA_PICKUP',
  'TIEMPO_MAXIMO_ESPERA_PENDIENTE',
  'CAPACIDAD_MAXIMA_ORDENES_DESPACHO',
  'CAPACIDAD_MAXIMA_ORDENES_PENDIENTES',
  'CAPACIDAD_MAXIMA_ORDENES_COCINA',
  'CAPACIDAD_MAXIMA_ORDENES_DESPACHO_PICKUP',
  'CAPACIDAD_MAXIMA_ORDENES_EN_RUTA'
];
