export const VALID_METRICS = [
  'ORDERS_PENDING_MAX',
  'KITCHEN_TIME_MAX_MINUTES',
  'DISPATCH_CAPACITY_MAX',
  'DELIVERY_TRAVEL_TIME_MAX_MINUTES',
  'DRIVER_ASSIGNMENT_TIMEOUT_MINUTES',
  'PICKUP_WAIT_TIME_MAX_MINUTES',
  'TOTAL_ORDER_CYCLE_MAX_MINUTES',
];
